### ISSUE TITLE
error at the first start  

### ISSUE THREAD

**Issue by n-haddag** [renatolond/mastodon-twitter-poster#242]
```
Puma starting in single mode...
* Version 3.12.1 (ruby 2.6.5-p114), codename: Llamas in Pajamas
* Min threads: 5, max threads: 5
* Environment: production
* Listening on tcp://0.0.0.0:3331
Use Ctrl-C to stop
[de4aadba-be82-43ed-8361-f4704f36ea7e] Started POST "/inbox" for 74.207.240.171 at 2019-10-22 11:44:22 +0000
[de4aadba-be82-43ed-8361-f4704f36ea7e]   
[de4aadba-be82-43ed-8361-f4704f36ea7e] ActionController::RoutingError (No route matches [POST] "/inbox"):
[de4aadba-be82-43ed-8361-f4704f36ea7e]   
[de4aadba-be82-43ed-8361-f4704f36ea7e] vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
[de4aadba-be82-43ed-8361-f4704f36ea7e] vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
[de4aadba-be82-43ed-8361-f4704f36ea7e] vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/rack/logger.rb:38:in `call_app'
[de4aadba-be82-43ed-8361-f4704f36ea7e] vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/rack/logger.rb:26:in `block in call'
[de4aadba-be82-43ed-8361-f4704f36ea7e] vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:71:in `block in tagged'
[de4aadba-be82-43ed-8361-f4704f36ea7e] vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:28:in `tagged'
[de4aadba-be82-43ed-8361-f4704f36ea7e] vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:71:in `tagged'
[de4aadba-be82-43ed-8361-f4704f36ea7e] vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/rack/logger.rb:26:in `call'
[de4aadba-be82-43ed-8361-f4704f36ea7e] vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
[de4aadba-be82-43ed-8361-f4704f36ea7e] vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/request_id.rb:27:in `call'
[de4aadba-be82-43ed-8361-f4704f36ea7e] vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/method_override.rb:22:in `call'
[de4aadba-be82-43ed-8361-f4704f36ea7e] vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/runtime.rb:22:in `call'
[de4aadba-be82-43ed-8361-f4704f36ea7e] vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
[de4aadba-be82-43ed-8361-f4704f36ea7e] vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/executor.rb:14:in `call'
[de4aadba-be82-43ed-8361-f4704f36ea7e] vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/static.rb:127:in `call'
[de4aadba-be82-43ed-8361-f4704f36ea7e] vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/sendfile.rb:111:in `call'
[de4aadba-be82-43ed-8361-f4704f36ea7e] vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/engine.rb:524:in `call'
[de4aadba-be82-43ed-8361-f4704f36ea7e] vendor/bundle/ruby/2.6.0/gems/puma-3.12.1/lib/puma/configuration.rb:227:in `call'
[de4aadba-be82-43ed-8361-f4704f36ea7e] vendor/bundle/ruby/2.6.0/gems/puma-3.12.1/lib/puma/server.rb:660:in `handle_request'
[de4aadba-be82-43ed-8361-f4704f36ea7e] vendor/bundle/ruby/2.6.0/gems/puma-3.12.1/lib/puma/server.rb:474:in `process_client'
[de4aadba-be82-43ed-8361-f4704f36ea7e] vendor/bundle/ruby/2.6.0/gems/puma-3.12.1/lib/puma/server.rb:334:in `block in run'
[de4aadba-be82-43ed-8361-f4704f36ea7e] vendor/bundle/ruby/2.6.0/gems/puma-3.12.1/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
[a866e432-e2cf-485c-84a1-585fed0a26fd] Started POST "/inbox" for 176.9.126.83 at 2019-10-22 11:44:32 +0000
```

**Comment by renatolond** [comment]
Hi! :)
Do you have a bit more info about how you started the command? Which version of ruby are you using? Did you do this post yourself?

**Comment by n-haddag** [comment]
hi @renatolond ,
i used this commade to start 
`RAILS_ENV=production PORT=3331 bundle exec puma -C config/puma.rb`
my ruby verions
`nhaddag@srv:~/cross$ ruby --version
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]
`

**Comment by renatolond** [comment]
Okay, I don't see an error with the start, the error is that something or someone did a post to `/inbox`, which does not exist in the crossposter. Maybe the crossposter is sharing the same address as a Mastodon instance?

**Comment by n-haddag** [comment]
Yes exactly I share the same address of my mastodon instance
https://masto.openalgeria.org

**Comment by renatolond** [comment]
Yeah, in that case, maybe the issue is that the crossposter will receive requests coming for your mastodon instance. The crossposter should be in a different domain (such as crosspost.openalgeria.org).

**Comment by n-haddag** [comment]
Yes my crosspost is here
https://cross.openalgeria.org

**Comment by renatolond** [comment]
Hmm, it seems fine to me. If you navigate to https://cross.openalgeria.org/sidekiq while logged in, can you see any issues?

**Comment by renatolond** [comment]
If you haven't yet, you have to add yourself as an admin, as described here: https://github.com/renatolond/mastodon-twitter-poster#admin-tasks

**Comment by n-haddag** [comment]
> Hmm, it seems fine to me. If you navigate to https://cross.openalgeria.org/sidekiq while logged in, can you see any issues?

Opss its not found 
![Capture d’écran du 2019-11-08 11-12-29](https://user-images.githubusercontent.com/39639882/68468679-ca04bc00-0218-11ea-9a1b-814792a66901.png)
I will  going to try to fix this.


> If you haven't yet, you have to add yourself as an admin, as described here: https://github.com/renatolond/mastodon-twitter-poster#admin-tasks

yes it's good I have defined the admin.

just a question : it's not a node version problem, because I use 10.15 version

**Comment by renatolond** [comment]
If you are seeing a 404 it might be because you're not logged with the admin user.

The node version should be fine with 10.15, node is only used to setup the assets (js and css) and your assets look good from here.

**Comment by n-haddag** [comment]
now it works, it was the firewall that blocked the port 3331
