### ISSUE TITLE
'HTTP::ConnectionError: failed to connect' on launch

### ISSUE THREAD

**Issue by dunn** [renatolond/mastodon-twitter-poster#503]
After filling in the values for `.env`, I get this error from the Ruby components when they try to start during `docker-compose up`:
```
web_1      | Puma starting in single mode...
web_1      | * Version 4.3.5 (ruby 2.7.2-p137), codename: Mysterious Traveller
web_1      | * Min threads: 5, max threads: 5
web_1      | * Environment: production
web_1      | ! Unable to load application: HTTP::ConnectionError: failed to connect: getaddrinfo: Name does not resolve
web_1      | bundler: failed to load command: puma (/crossposter/vendor/bundle/ruby/2.7.0/bin/puma)
web_1      | HTTP::ConnectionError: failed to connect: getaddrinfo: Name does not resolve
web_1      |   /crossposter/vendor/bundle/ruby/2.7.0/gems/http-4.4.1/lib/http/timeout/null.rb:21:in `initialize'
web_1      |   /crossposter/vendor/bundle/ruby/2.7.0/gems/http-4.4.1/lib/http/timeout/null.rb:21:in `open'
web_1      |   /crossposter/vendor/bundle/ruby/2.7.0/gems/http-4.4.1/lib/http/timeout/null.rb:21:in `connect'
web_1      |   /crossposter/vendor/bundle/ruby/2.7.0/gems/http-4.4.1/lib/http/connection.rb:43:in `initialize'
web_1      |   /crossposter/vendor/bundle/ruby/2.7.0/gems/http-4.4.1/lib/http/client.rb:71:in `new'
web_1      |   /crossposter/vendor/bundle/ruby/2.7.0/gems/http-4.4.1/lib/http/client.rb:71:in `perform'
web_1      |   /crossposter/vendor/bundle/ruby/2.7.0/gems/http-4.4.1/lib/http/client.rb:31:in `request'
web_1      |   /crossposter/vendor/bundle/ruby/2.7.0/gems/http-4.4.1/lib/http/chainable.rb:27:in `post'
web_1      |   /crossposter/vendor/bundle/ruby/2.7.0/bundler/gems/twitter-cb40cd210ff8/lib/twitter/rest/oauth.rb:30:in `token'
web_1      |   /crossposter/vendor/bundle/ruby/2.7.0/bundler/gems/twitter-cb40cd210ff8/lib/twitter/headers.rb:41:in `auth_header'
web_1      |   /crossposter/vendor/bundle/ruby/2.7.0/bundler/gems/twitter-cb40cd210ff8/lib/twitter/headers.rb:30:in `request_headers'
web_1      |   /crossposter/vendor/bundle/ruby/2.7.0/bundler/gems/twitter-cb40cd210ff8/lib/twitter/rest/request.rb:62:in `set_multipart_options!'
web_1      |   /crossposter/vendor/bundle/ruby/2.7.0/bundler/gems/twitter-cb40cd210ff8/lib/twitter/rest/request.rb:28:in `initialize'
web_1      |   /crossposter/vendor/bundle/ruby/2.7.0/bundler/gems/twitter-cb40cd210ff8/lib/twitter/rest/utils.rb:50:in `new'
web_1      |   /crossposter/vendor/bundle/ruby/2.7.0/bundler/gems/twitter-cb40cd210ff8/lib/twitter/rest/utils.rb:50:in `perform_request'
web_1      |   /crossposter/vendor/bundle/ruby/2.7.0/bundler/gems/twitter-cb40cd210ff8/lib/twitter/rest/utils.rb:72:in `perform_request_with_object'
web_1      |   /crossposter/vendor/bundle/ruby/2.7.0/bundler/gems/twitter-cb40cd210ff8/lib/twitter/rest/utils.rb:57:in `perform_get_with_object'
web_1      |   /crossposter/vendor/bundle/ruby/2.7.0/bundler/gems/twitter-cb40cd210ff8/lib/twitter/rest/help.rb:19:in `configuration'
web_1      |   /crossposter/config/initializers/toot_transformer.rb:12:in `<main>'
```
full trace: https://gist.github.com/dunn/128846e29021fec5bc431856e910154a

i don't think the puma error is related, since it doesn't appear in the sidekiq container logs, where this error also occurs: https://gist.github.com/dunn/f7be9a20c11b2ac24f93a9899304f2e0

**Comment by dunn** [comment]
i did try upgrading puma, as well as using the upstream twitter gem and adjusting the docker-compose networking, but nothing seemed to work.

**Comment by renatolond** [comment]
Hey, @dunn !
From the backtrace it seems it cannot connect to twitter, are you able to `curl https://twitter.com` from that machine?

**Comment by dunn** [comment]
yeah, it can connect from outside the container and inside; i added a test step to the dockerfile and it can reach twitter.com:
```
Step 22/23 : RUN curl -IL https://twitter.com
 ---> Running in bb946ab2cc5c
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:--HTTP/2 400    0
cache-control: no-cache, no-store, must-revalidate, pre-check=0, post-check=0
content-security-policy: connect-src 'self' blob: https://*.giphy.com https://*.pscp.tv https://*.video.pscp.tv https://*.twimg.com https://api.twitter.com https://api-stream.twitter.com https://ads-api.twitter.com https://caps.twitter.com https://media.riffsy.com https://pay.twitter.com https://sentry.io https://ton.twitter.com https://twitter.com https://upload.twitter.com https://www.google-analytics.com https://app.link https://api2.branch.io https://bnc.lt https://vmap.snappytv.com https://vmapstage.snappytv.com https://vmaprel.snappytv.com https://vmap.grabyo.com https://dhdsnappytv-vh.akamaihd.net https://pdhdsnappytv-vh.akamaihd.net https://mdhdsnappytv-vh.akamaihd.net https://mdhdsnappytv-vh.akamaihd.net https://mpdhdsnappytv-vh.akamaihd.net https://mmdhdsnappytv-vh.akamaihd.net https://mdhdsnappytv-vh.akamaihd.net https://mpdhdsnappytv-vh.akamaihd.net https://mmdhdsnappytv-vh.akamaihd.net https://dwo3ckksxlb0v.cloudfront.net ; default-src 'self'; form-action 'self' https://twitter.com https://*.twitter.com; font-src 'self' https://*.twimg.com; frame-src 'self' https://twitter.com https://mobile.twitter.com https://pay.twitter.com https://cards-frame.twitter.com ; img-src 'self' blob: data: https://*.cdn.twitter.com https://ton.twitter.com https://*.twimg.com https://analytics.twitter.com https://cm.g.doubleclick.net https://www.google-analytics.com https://www.periscope.tv https://www.pscp.tv https://media.riffsy.com https://*.giphy.com https://*.pscp.tv https://*.periscope.tv https://prod-periscope-profile.s3-us-west-2.amazonaws.com https://platform-lookaside.fbsbx.com https://scontent.xx.fbcdn.net https://*.googleusercontent.com; manifest-src 'self'; media-src 'self' blob: https://twitter.com https://*.twimg.com https://*.vine.co https://*.pscp.tv https://*.video.pscp.tv https://*.giphy.com https://media.riffsy.com https://dhdsnappytv-vh.akamaihd.net https://pdhdsnappytv-vh.akamaihd.net https://mdhdsnappytv-vh.akamaihd.net https://mdhdsnappytv-vh.akamaihd.net https://mpdhdsnappytv-vh.akamaihd.net https://mmdhdsnappytv-vh.akamaihd.net https://mdhdsnappytv-vh.akamaihd.net https://mpdhdsnappytv-vh.akamaihd.net https://mmdhdsnappytv-vh.akamaihd.net https://dwo3ckksxlb0v.cloudfront.net; object-src 'none'; script-src 'self' 'unsafe-inline' https://*.twimg.com   https://www.google-analytics.com https://twitter.com https://app.link  'nonce-ZDY1NzFjZTUtYTZhMS00OGQwLWEwODctYjhkNDU5YjdlNjM5'; style-src 'self' 'unsafe-inline' https://*.twimg.com; worker-src 'self' blob:; report-uri https://twitter.com/i/csp_report?a=O5RXE%3D%3D%3D&ro=false
content-type: text/html; charset=utf-8
cross-origin-opener-policy: same-origin
date: Thu, 28 Jan 2021 08:21:44 GMT
expiry: Tue, 31 Mar 1981 05:00:00 GMT
last-modified: Thu, 28 Jan 2021 08:21:44 GMT
pragma: no-cache
server: tsa_a
set-cookie: personalization_id="v1_oaX/fFbhdL79/k/0WBJyUw=="; Max-Age=63072000; Expires=Sat, 28 Jan 2023 08:21:44 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None
set-cookie: guest_id=v1%3A161182210491962986; Max-Age=63072000; Expires=Sat, 28 Jan 2023 08:21:44 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None
strict-transport-security: max-age=631138519
x-connection-hash: 1c55c4212e810239bf313ecf5eed134b
x-content-type-options: nosniff
x-frame-options: DENY
x-powered-by: Express
x-response-time: 17
x-xss-protection: 0

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
```
are you unable to replicate this on a fresh build?

**Comment by renatolond** [comment]
If I run `docker run -e "CROSSPOSTER_DOMAIN=localhost" -e "CROSSPOSTER_ADMIN_FEDI_ADDRESS=foo" -e "CROSSPOSTER_ADMIN_FEDI_AT=foo" <image SHA> rails console`, I get `Missing Twitter credentials`, which happens because I didn't add twitter credentials and I get a Bad Authentication Data, and if I do add credentials, it starts normally over here, can you try that over there?

**Comment by dunn** [comment]
on this machine, i get the same thing:
```
  docker run -e "CROSSPOSTER_DOMAIN=localhost" -e "CROSSPOSTER_ADMIN_FEDI_ADD
RESS=foo" -e "CROSSPOSTER_ADMIN_FEDI_AT=foo" 3644ddd414be rails console
/crossposter/vendor/bundle/ruby/2.7.0/gems/http-4.4.1/lib/http/timeout/null.rb:21:in `initialize': failed to connect: getaddrinfo: Name does not resolve (HTTP::ConnectionError)
```

but on another machine (windows with gitbash instead of macos, if it's relevant), i get the correct behavior.  so something funny's going on with my environment.

sorry for the false alarm!
