### ISSUE TITLE
BUG: An issue with @babel when attempting to precompile assets

### ISSUE THREAD

**Issue by phobos-dthorga** [renatolond/mastodon-twitter-poster#522]
Hello everyone!

I'm encountering an issue with `@babel` (I think?) when I attempt to `RAILS_ENV="production" bundle exec rake assets:precompile` after performing all the previous stages of setting up the Twitter <-> Mastodon Crossposter as mentioned by `README.md` within the root of the Git repository.

The specific error which I get is the following:

```bash
awoo_link@arctic:~/public_html$ RAILS_ENV="production" bundle exec rake assets:precompile
Using hardcoded values for twitter url length
yarn install v1.22.5
[1/6] Validating package.json...
[2/6] Resolving packages...
[3/6] Fetching packages...
info fsevents@1.2.11: The platform "linux" is incompatible with this module.
info "fsevents@1.2.11" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/6] Linking dependencies...
warning " > webpack-cli@3.3.11" has unmet peer dependency "webpack@4.x.x".
warning " > webpack-dev-server@3.10.3" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning "webpack-dev-server > webpack-dev-middleware@3.7.2" has unmet peer dependency "webpack@^4.0.0".
[5/6] Building fresh packages...
[6/6] Cleaning modules...
Done in 11.24s.
yarn install v1.22.5
[1/6] Validating package.json...
[2/6] Resolving packages...
[3/6] Fetching packages...
info fsevents@1.2.11: The platform "linux" is incompatible with this module.
info "fsevents@1.2.11" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/6] Linking dependencies...
warning " > webpack-cli@3.3.11" has unmet peer dependency "webpack@4.x.x".
warning " > webpack-dev-server@3.10.3" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning "webpack-dev-server > webpack-dev-middleware@3.7.2" has unmet peer dependency "webpack@^4.0.0".
[5/6] Building fresh packages...
[6/6] Cleaning modules...
Done in 9.45s.
Compiling...
Compilation failed:
Hash: 7c00ef60c5f6faa11e39
Version: webpack 4.42.0
Time: 569ms
Built at: 03/01/2021 9:35:19 AM
 2 assets
Entrypoint application = js/application-ad7430adaec19cc9f18b.js js/application-ad7430adaec19cc9f18b.js.map
[0] ./app/javascript/packs/application.js 3.04 KiB {0} [built] [failed] [1 error]

ERROR in ./app/javascript/packs/application.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module '/home/awoo_link/public_html/node_modules/@babel/compat-data/data/corejs3-shipped-proposals'
    at createEsmNotFoundErr (internal/modules/cjs/loader.js:842:15)
    at finalizeEsmResolution (internal/modules/cjs/loader.js:835:15)
    at resolveExports (internal/modules/cjs/loader.js:424:14)
    at Function.Module._findPath (internal/modules/cjs/loader.js:464:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:802:27)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (/home/awoo_link/public_html/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/home/awoo_link/public_html/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js:10:55)
    at Module._compile (/home/awoo_link/public_html/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (/home/awoo_link/public_html/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/home/awoo_link/public_html/node_modules/@babel/preset-env/lib/index.js:29:44)
    at Module._compile (/home/awoo_link/public_html/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (/home/awoo_link/public_html/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at module.exports (/home/awoo_link/public_html/babel.config.js:29:9)
    at readConfigJS (/home/awoo_link/public_html/node_modules/@babel/core/lib/config/files/configuration.js:202:15)
    at readConfigJS.next (<anonymous>)
    at Function.<anonymous> (/home/awoo_link/public_html/node_modules/@babel/core/lib/gensync-utils/async.js:26:3)
    at Generator.next (<anonymous>)
    at evaluateSync (/home/awoo_link/public_html/node_modules/gensync/index.js:244:28)
    at Function.sync (/home/awoo_link/public_html/node_modules/gensync/index.js:84:14)
    at sync (/home/awoo_link/public_html/node_modules/@babel/core/lib/gensync-utils/async.js:66:25)
    at sync (/home/awoo_link/public_html/node_modules/gensync/index.js:177:19)
    at onFirstPause (/home/awoo_link/public_html/node_modules/gensync/index.js:204:19)
    at Generator.next (<anonymous>)
    at cachedFunction (/home/awoo_link/public_html/node_modules/@babel/core/lib/config/caching.js:68:46)
    at cachedFunction.next (<anonymous>)
    at evaluateSync (/home/awoo_link/public_html/node_modules/gensync/index.js:244:28)

awoo_link@arctic:~/public_html$
```

Any assistance regarding this matter would be sincerely appreciated, thank you.

**Comment by renatolond** [comment]
Hi! Which version of node are you running? (you can check with `node -v`)

**Comment by vincib** [comment]
same bug here, using node 12.21.0

**Comment by renatolond** [comment]
I'm closing this, but if you need more help just re-open it :)
