### ISSUE TITLE
no implicit conversion of Symbol into Integer for twitter_config.short_url_length

### ISSUE THREAD

**Issue by HugoPoi** [renatolond/mastodon-twitter-poster#571]
the app crash immediately

```
Puma starting in single mode...,
* Version 4.3.8 (ruby 2.7.1-p83), codename: Mysterious Traveller,
* Min threads: 5, max threads: 5,
* Environment: production,
/crossposter/vendor/bundle/ruby/2.7.0/gems/faraday-0.15.4/lib/faraday/options.rb:166: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead,
/crossposter/vendor/bundle/ruby/2.7.0/gems/faraday-0.15.4/lib/faraday/options.rb:166: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead,
/crossposter/vendor/bundle/ruby/2.7.0/gems/faraday-0.15.4/lib/faraday/options.rb:166: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead,
/crossposter/vendor/bundle/ruby/2.7.0/gems/faraday-0.15.4/lib/faraday/options.rb:166: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead,
/crossposter/vendor/bundle/ruby/2.7.0/gems/faraday-0.15.4/lib/faraday/options.rb:166: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead,
! Unable to load application: TypeError: no implicit conversion of Symbol into Integer,
bundler: failed to load command: puma (/crossposter/vendor/bundle/ruby/2.7.0/bin/puma),
TypeError: no implicit conversion of Symbol into Integer,
  /crossposter/vendor/bundle/ruby/2.7.0/bundler/gems/twitter-cb40cd210ff8/lib/twitter/base.rb:128:in `[]',
  /crossposter/vendor/bundle/ruby/2.7.0/bundler/gems/twitter-cb40cd210ff8/lib/twitter/base.rb:128:in `attr_falsey_or_empty?',
  /crossposter/vendor/bundle/ruby/2.7.0/bundler/gems/twitter-cb40cd210ff8/lib/twitter/base.rb:86:in `block in define_attribute_method',
  /crossposter/vendor/bundle/ruby/2.7.0/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:117:in `call',
  /crossposter/vendor/bundle/ruby/2.7.0/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:117:in `block (3 levels) in create_memoized_method',
  /crossposter/vendor/bundle/ruby/2.7.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:63:in `block (3 levels) in fetch',
  /crossposter/vendor/bundle/ruby/2.7.0/gems/thread_safe-0.3.6/lib/thread_safe/cache.rb:56:in `fetch',
  /crossposter/vendor/bundle/ruby/2.7.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:62:in `block (2 levels) in fetch',
  /crossposter/vendor/bundle/ruby/2.7.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:61:in `synchronize',
  /crossposter/vendor/bundle/ruby/2.7.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:61:in `block in fetch',
  /crossposter/vendor/bundle/ruby/2.7.0/gems/thread_safe-0.3.6/lib/thread_safe/cache.rb:56:in `fetch',
  /crossposter/vendor/bundle/ruby/2.7.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:60:in `fetch',
  /crossposter/vendor/bundle/ruby/2.7.0/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:116:in `block (2 levels) in create_memoized_method',
  /crossposter/config/initializers/toot_transformer.rb:13:in `<main>',
  /crossposter/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load',
  /crossposter/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load',
  /crossposter/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:285:in `block in load',
  /crossposter/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency',
  /crossposter/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:285:in `load',
  /crossposter/vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.4/lib/rails/engine.rb:663:in `block in load_config_initializer',
  /crossposter/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/notifications.rb:170:in `instrument',
  /crossposter/vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.4/lib/rails/engine.rb:662:in `load_config_initializer',
  /crossposter/vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.4/lib/rails/engine.rb:620:in `block (2 levels) in <class:Engine>',
  /crossposter/vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.4/lib/rails/engine.rb:619:in `each',
  /crossposter/vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.4/lib/rails/engine.rb:619:in `block in <class:Engine>',
  /crossposter/vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.4/lib/rails/initializable.rb:32:in `instance_exec',
  /crossposter/vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.4/lib/rails/initializable.rb:32:in `run',
  /crossposter/vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.4/lib/rails/initializable.rb:61:in `block in run_initializers',
  /usr/local/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each',
  /usr/local/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component',
  /usr/local/lib/ruby/2.7.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from',
  /usr/local/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from',
  /usr/local/lib/ruby/2.7.0/tsort.rb:421:in `block in each_strongly_connected_component_from',
  /crossposter/vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.4/lib/rails/initializable.rb:50:in `each',
  /crossposter/vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.4/lib/rails/initializable.rb:50:in `tsort_each_child',
  /usr/local/lib/ruby/2.7.0/tsort.rb:415:in `call',
  /usr/local/lib/ruby/2.7.0/tsort.rb:415:in `each_strongly_connected_component_from',
  /usr/local/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component',
  /usr/local/lib/ruby/2.7.0/tsort.rb:347:in `each',
  /usr/local/lib/ruby/2.7.0/tsort.rb:347:in `call',
  /usr/local/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component',
  /usr/local/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each',
  /usr/local/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each',
  /crossposter/vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.4/lib/rails/initializable.rb:60:in `run_initializers',
  /crossposter/vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.4/lib/rails/application.rb:361:in `initialize!',
  /crossposter/config/environment.rb:5:in `<top (required)>',
  config.ru:3:in `require_relative',
  config.ru:3:in `block in <main>',
  /crossposter/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval',
  /crossposter/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string',
  /crossposter/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file',
  /crossposter/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file',
  /crossposter/vendor/bundle/ruby/2.7.0/gems/puma-4.3.8/lib/puma/configuration.rb:321:in `load_rackup',
  /crossposter/vendor/bundle/ruby/2.7.0/gems/puma-4.3.8/lib/puma/configuration.rb:246:in `app',
  /crossposter/vendor/bundle/ruby/2.7.0/gems/puma-4.3.8/lib/puma/runner.rb:155:in `load_and_bind',
  /crossposter/vendor/bundle/ruby/2.7.0/gems/puma-4.3.8/lib/puma/single.rb:98:in `run',
  /crossposter/vendor/bundle/ruby/2.7.0/gems/puma-4.3.8/lib/puma/launcher.rb:172:in `run',
  /crossposter/vendor/bundle/ruby/2.7.0/gems/puma-4.3.8/lib/puma/cli.rb:80:in `run',
  /crossposter/vendor/bundle/ruby/2.7.0/gems/puma-4.3.8/bin/puma:10:in `<top (required)>',
  /crossposter/vendor/bundle/ruby/2.7.0/bin/puma:23:in `load',
  /crossposter/vendor/bundle/ruby/2.7.0/bin/puma:23:in `<top (required)>',
```
Ruby 2.7 ?
In Twitter there no default value for short_url_length nor short_url_length_https, its a alias with no type, but I'm a noob in Ruby.

The Dockerfile use ruby 2.7 but not in match `.ruby-version`, but I was running an old version of the app with this.
I try to downgrade ruby in the Dockerfile, cause more problems ...

**Comment by HugoPoi** [comment]
Workarround is to comment line 13-14 in `config/initializers/toot_transformer.rb`

**Comment by renatolond** [comment]
Hi! It seems you're missing twiter credentials for the call. The error seems to happen when calling twitter, which will be done to get the url length from their API. Do you have `TWITTER_CLIENT_ID` and `TWITTER_CLIENT_SECRET` defined as indicated in the [setup](https://github.com/renatolond/mastodon-twitter-poster#setup) part?

**Comment by renatolond** [comment]
Ah, I see, there was a change in Twitter's side, see https://github.com/sferik/twitter/pull/998, I'll pick this up when I have some time :)
Thanks for reporting it!

**Comment by rriemann-eu** [comment]
I am running on docker and hit the same problem
