### ISSUE TITLE
Oauth Issue with Docker Install

### ISSUE THREAD

**Issue by probgoblin** [renatolond/mastodon-twitter-poster#827]
I am receiving the following error when trying to connect a Twitter account the cross poster:
```
I, [2022-10-16T00:48:49.787410 #1]  INFO -- : [18d5dc45-083e-4553-a641-0f4807c45058] Started POST "/users/auth/twitter" for 184.190.140.128 at 2022-10-16 00:48:49 +0000
I, [2022-10-16T00:48:49.789531 #1]  INFO -- omniauth: (twitter) Request phase initiated.
F, [2022-10-16T00:48:49.883788 #1] FATAL -- : [18d5dc45-083e-4553-a641-0f4807c45058]
[18d5dc45-083e-4553-a641-0f4807c45058] OAuth::Unauthorized (401 Unauthorized):
[18d5dc45-083e-4553-a641-0f4807c45058]
[18d5dc45-083e-4553-a641-0f4807c45058] oauth (0.5.8) lib/oauth/consumer.rb:259:in `token_request'
[18d5dc45-083e-4553-a641-0f4807c45058] oauth (0.5.8) lib/oauth/consumer.rb:169:in `get_request_token'
[18d5dc45-083e-4553-a641-0f4807c45058] omniauth-oauth (1.2.0) lib/omniauth/strategies/oauth.rb:28:in `request_phase'
[18d5dc45-083e-4553-a641-0f4807c45058] omniauth-twitter (1.4.0) lib/omniauth/strategies/twitter.rb:61:in `request_phase'
[18d5dc45-083e-4553-a641-0f4807c45058] omniauth (1.9.1) lib/omniauth/strategy.rb:226:in `request_call'
[18d5dc45-083e-4553-a641-0f4807c45058] omniauth (1.9.1) lib/omniauth/strategy.rb:188:in `call!'
[18d5dc45-083e-4553-a641-0f4807c45058] omniauth (1.9.1) lib/omniauth/strategy.rb:169:in `call'
[18d5dc45-083e-4553-a641-0f4807c45058] http_accept_language (2.1.1) lib/http_accept_language/middleware.rb:14:in `call'
[18d5dc45-083e-4553-a641-0f4807c45058] warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
[18d5dc45-083e-4553-a641-0f4807c45058] warden (1.2.9) lib/warden/manager.rb:34:in `catch'
[18d5dc45-083e-4553-a641-0f4807c45058] warden (1.2.9) lib/warden/manager.rb:34:in `call'
[18d5dc45-083e-4553-a641-0f4807c45058] rack (2.2.4) lib/rack/tempfile_reaper.rb:15:in `call'
[18d5dc45-083e-4553-a641-0f4807c45058] rack (2.2.4) lib/rack/etag.rb:27:in `call'
[18d5dc45-083e-4553-a641-0f4807c45058] rack (2.2.4) lib/rack/conditional_get.rb:40:in `call'
[18d5dc45-083e-4553-a641-0f4807c45058] rack (2.2.4) lib/rack/head.rb:12:in `call'
[18d5dc45-083e-4553-a641-0f4807c45058] actionpack (7.0.3.1) lib/action_dispatch/http/permissions_policy.rb:38:in `call'
[18d5dc45-083e-4553-a641-0f4807c45058] actionpack (7.0.3.1) lib/action_dispatch/http/content_security_policy.rb:36:in `call'
[18d5dc45-083e-4553-a641-0f4807c45058] rack (2.2.4) lib/rack/session/abstract/id.rb:266:in `context'
[18d5dc45-083e-4553-a641-0f4807c45058] rack (2.2.4) lib/rack/session/abstract/id.rb:260:in `call'
[18d5dc45-083e-4553-a641-0f4807c45058] actionpack (7.0.3.1) lib/action_dispatch/middleware/cookies.rb:697:in `call'
[18d5dc45-083e-4553-a641-0f4807c45058] actionpack (7.0.3.1) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
[18d5dc45-083e-4553-a641-0f4807c45058] activesupport (7.0.3.1) lib/active_support/callbacks.rb:99:in `run_callbacks'
[18d5dc45-083e-4553-a641-0f4807c45058] actionpack (7.0.3.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
[18d5dc45-083e-4553-a641-0f4807c45058] actionpack (7.0.3.1) lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'
[18d5dc45-083e-4553-a641-0f4807c45058] actionpack (7.0.3.1) lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'
[18d5dc45-083e-4553-a641-0f4807c45058] railties (7.0.3.1) lib/rails/rack/logger.rb:40:in `call_app'
[18d5dc45-083e-4553-a641-0f4807c45058] railties (7.0.3.1) lib/rails/rack/logger.rb:25:in `block in call'
[18d5dc45-083e-4553-a641-0f4807c45058] activesupport (7.0.3.1) lib/active_support/tagged_logging.rb:114:in `block in tagged'
[18d5dc45-083e-4553-a641-0f4807c45058] activesupport (7.0.3.1) lib/active_support/tagged_logging.rb:38:in `tagged'
[18d5dc45-083e-4553-a641-0f4807c45058] activesupport (7.0.3.1) lib/active_support/tagged_logging.rb:114:in `tagged'
[18d5dc45-083e-4553-a641-0f4807c45058] railties (7.0.3.1) lib/rails/rack/logger.rb:25:in `call'
[18d5dc45-083e-4553-a641-0f4807c45058] actionpack (7.0.3.1) lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
[18d5dc45-083e-4553-a641-0f4807c45058] actionpack (7.0.3.1) lib/action_dispatch/middleware/request_id.rb:26:in `call'
[18d5dc45-083e-4553-a641-0f4807c45058] rack (2.2.4) lib/rack/method_override.rb:24:in `call'
[18d5dc45-083e-4553-a641-0f4807c45058] rack (2.2.4) lib/rack/runtime.rb:22:in `call'
[18d5dc45-083e-4553-a641-0f4807c45058] actionpack (7.0.3.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
[18d5dc45-083e-4553-a641-0f4807c45058] actionpack (7.0.3.1) lib/action_dispatch/middleware/static.rb:23:in `call'
[18d5dc45-083e-4553-a641-0f4807c45058] rack (2.2.4) lib/rack/sendfile.rb:110:in `call'
[18d5dc45-083e-4553-a641-0f4807c45058] actionpack (7.0.3.1) lib/action_dispatch/middleware/host_authorization.rb:131:in `call'
[18d5dc45-083e-4553-a641-0f4807c45058] railties (7.0.3.1) lib/rails/engine.rb:530:in `call'
[18d5dc45-083e-4553-a641-0f4807c45058] puma (5.6.4) lib/puma/configuration.rb:252:in `call'
[18d5dc45-083e-4553-a641-0f4807c45058] puma (5.6.4) lib/puma/request.rb:77:in `block in handle_request'
[18d5dc45-083e-4553-a641-0f4807c45058] puma (5.6.4) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
[18d5dc45-083e-4553-a641-0f4807c45058] puma (5.6.4) lib/puma/request.rb:76:in `handle_request'
[18d5dc45-083e-4553-a641-0f4807c45058] puma (5.6.4) lib/puma/server.rb:441:in `process_client'
[18d5dc45-083e-4553-a641-0f4807c45058] puma (5.6.4) lib/puma/thread_pool.rb:147:in `block in spawn_thread'
```

Steps to reproduce:

Created new Twitter application: 
OAuth 2.0, Read & Write Permissions, Web App
Callback of https://CROSSPOSTERADDRESS/users/auth/twitter/callback
Website of https://CROSSPOSTERADDRESS

Cloned the git repository to my host machine and populated an .env file with the TWITTER_CLIENT_ID set to the app's Client ID and TWITTER_CLIENT_SECRET set to the app's Client Secret from the Twitter application, both wrapped in single quotes due to special characters, and a SECRET_KEY_BASE set to the results of `openssl rand -hex 64` (also wrapped in single quotes, although I get the same results without).

Running `sudo docker compose up -d --build` and then `sudo docker compose run --rm web bundle exec rake db:setup`. The site is accessible but I receive the following message when clicking on the Twitter button: "We're sorry, but something went wrong.
If you are the application owner check the logs for more information."

**Comment by renatolond** [comment]
Hmm, from what you're describing the configuration looks correct.
It does seem similar to https://github.com/arunagw/omniauth-twitter/issues/118, which seems to be an issue with the callback URL. Have you managed to run it locally? (if you add localhost as a callback and then run it locally with docker)

**Comment by probgoblin** [comment]
I have not, but this may be due to issues I'm having with the postgres container for the server itself. Once I get some time later this week I'll either update or close this issue. Thank you.

**Comment by probgoblin** [comment]
This does not seem to be an issue with the Pleroma server. Let me try running this in a container on another machine. Would the callback URL be "https://127.0.0.1:portnumber/users/auth/twitter/callback" ?

**Comment by probgoblin** [comment]
When trying to build on Windows I get the following:

```
> [stage-1 13/13] RUN bundle exec rake assets:precompile   TWITTER_CLIENT_SECRET=precompile_placeholder   TWITTER_CLIENT_ID=precompile_placeholder   SECRET_KEY_BASE=precompile_placeholder   CROSSPOSTER_DOMAIN=precompile_placeholder   CROSSPOSTER_ADMIN_FEDI_ADDRESS=precompile_placeholder   CROSSPOSTER_ADMIN_FEDI_AT=precompile_placeholder:
': No such file or directory'ruby
------
failed to solve: executor failed running [/bin/sh -c bundle exec rake assets:precompile   TWITTER_CLIENT_SECRET=precompile_placeholder   TWITTER_CLIENT_ID=precompile_placeholder   SECRET_KEY_BASE=precompile_placeholder   CROSSPOSTER_DOMAIN=precompile_placeholder   CROSSPOSTER_ADMIN_FEDI_ADDRESS=precompile_placeholder   CROSSPOSTER_ADMIN_FEDI_AT=precompile_placeholder]: exit code: 127
```

Would hardcoding those values in to the Dockerfile have any impact on the final image?

**Comment by renatolond** [comment]
Hmm, I think you could still override them with the env vars, so probably worth a try :)

**Comment by Lurkars** [comment]
I run into the same issue, the problem is simple
> The credentials that they give you need to be added to TWITTER_CLIENT_ID and TWITTER_CLIENT_SECRET.
This is wrong!!

In pre setup it's stated out as
> You need a consumer key (on our side TWITTER_CLIENT_ID) and consumer secret (on our side TWITTER_CLIENT_SECRET).

"consumer key" is the API key of your app, not the client_id/secret of the OAUTH2 part! So change it to those keys worked for me!

**Comment by probgoblin** [comment]
This did confirm the issue with Twitter authorization.
