### ISSUE TITLE
Simple rake tasks do twitter requests

### ISSUE THREAD

**Issue by sammy8806** [renatolond/mastodon-twitter-poster#98]
If I try to do something simple as `bundle exec rake db:migrate:status` the application tries to do twitter requests which could lead to:

```
~$ RAILS_ENV=production bundle exec rake db:migrate:status
rake aborted!
Twitter::Error::TooManyRequests: Rate limit exceeded
/srv/mastodon-twitter-poster/vendor/bundle/ruby/2.4.0/bundler/gems/twitter-b1ddf5ed5d4b/lib/twitter/rest/request.rb:89:in `fail_or_return_response_body'
/srv/mastodon-twitter-poster/vendor/bundle/ruby/2.4.0/bundler/gems/twitter-b1ddf5ed5d4b/lib/twitter/rest/request.rb:44:in `perform'
/srv/mastodon-twitter-poster/vendor/bundle/ruby/2.4.0/bundler/gems/twitter-b1ddf5ed5d4b/lib/twitter/rest/utils.rb:50:in `perform_request'
/srv/mastodon-twitter-poster/vendor/bundle/ruby/2.4.0/bundler/gems/twitter-b1ddf5ed5d4b/lib/twitter/rest/utils.rb:72:in `perform_request_with_object'
/srv/mastodon-twitter-poster/vendor/bundle/ruby/2.4.0/bundler/gems/twitter-b1ddf5ed5d4b/lib/twitter/rest/utils.rb:57:in `perform_get_with_object'
/srv/mastodon-twitter-poster/vendor/bundle/ruby/2.4.0/bundler/gems/twitter-b1ddf5ed5d4b/lib/twitter/rest/help.rb:19:in `configuration'
/srv/mastodon-twitter-poster/config/initializers/toot_transformer.rb:8:in `<top (required)>'
/srv/mastodon-twitter-poster/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:286:in `load'
...
```

**Comment by renatolond** [comment]
Yeah, it started after I changed the crossposter to use sidekiq, I'll look into it :)
